// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwlV0ADc7ZKE-bE9A0rEhqyK0rPY3SdE',
    appId: '1:1083738059485:android:c877fb3627e1fb1dafa134',
    messagingSenderId: '1083738059485',
    projectId: 'exitnow-aefd9',
    storageBucket: 'exitnow-aefd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvRp9hxfoTPj96sin61rORcxHUZQ9d2AE',
    appId: '1:1083738059485:ios:91ed8ea64e1a9d0fafa134',
    messagingSenderId: '1083738059485',
    projectId: 'exitnow-aefd9',
    storageBucket: 'exitnow-aefd9.appspot.com',
    iosClientId: '1083738059485-jvvubv9rrhonjog9ahl9h103j7oj3fu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.exitNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvRp9hxfoTPj96sin61rORcxHUZQ9d2AE',
    appId: '1:1083738059485:ios:91ed8ea64e1a9d0fafa134',
    messagingSenderId: '1083738059485',
    projectId: 'exitnow-aefd9',
    storageBucket: 'exitnow-aefd9.appspot.com',
    iosClientId: '1083738059485-jvvubv9rrhonjog9ahl9h103j7oj3fu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.exitNow',
  );
}
